RideSharingAPP.WEB/Models/AccountInformationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RideSharingApp.WEB.Models
{
    public class AccountInformationViewModel
    {
        public int id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string DynamicSalt { get; set; }
        public string Email { get; set; }
    }
}

RideSharingAPP.WEB/Models/CarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RideSharingApp.WEB.Models
{
    public class CarViewModel
    {
        public int id { get; set; }
        public string Mark { get; set; }
        public string Model { get; set; }
        public int YearOfIssue { get; set; }
        public string RegistrationNumber { get; set; }
        public string Comments { get; set; }
        public bool Deleted { get; set; }
    }
}

RideSharingAPP.WEB/Models/ClientViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RideSharingApp.WEB.Models
{
    public class ClientViewModel
    {
        public int id { get; set; }
        public DateTime DateOfRegistration { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Telephone { get; set; }
        public string Comments { get; set; }
        public bool Enabled { get; set; }
        public string Reason_for_blocking { get; set; }
    }
}

RideSharingAPP.WEB/Models/CompanionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RideSharingApp.WEB.Models
{
    public class CompanionViewModel
    {
        public int ClientId { get; set; }

        public int PassingPointId { get; set; }
    }
}

RideSharingAPP.WEB/Models/DriverLicensesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RideSharingApp.WEB.Models
{
    public class DriverLicensesViewModel
    {
        public int id { get; set; }
        public DateTime DateOfReceiving { get; set; }
        public DateTime ExpirationDate { get; set; }
        public string DriverLicensesNumber { get; set; }
        public string IssuingAuthority { get; set; }
        public Enum Categories { get; set; }
    }
}

RideSharingAPP.WEB/Models/DriverViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RideSharingApp.WEB.Models
{
    public class DriverViewModel
    {
        public int id { get; set; }
        public DateTime DateOfRegistration { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Telephone { get; set; }
        public string Comments { get; set; }
        public bool Enabled { get; set; }
        public string ReasonForBlocking { get; set; }
    }
}

RideSharingAPP.WEB/Models/PassingPointViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RideSharingApp.WEB.Models
{
    public class PassingPointViewModel
    {
        public int id { get; set; }
        public string OriginCoordinates { get; set; }
        public string EndCoordinates { get; set; }
        public DateTime DateAndTimeOfDepartue { get; set; }
        public DateTime DateAndTimeOfArrival { get; set; }
        public decimal Cost { get; set; }
        public int NumberPointOfThisTrip { get; set; }
        public bool Periodic { get; set; }
    }
}

RideSharingAPP.WEB/Models/TripViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RideSharingApp.WEB.Models
{
    public class TripViewModel
    {
        public int id { get; set; }
        public int NumberOfSeats { get; set; }
        public Enum Status { get; set; }
        public DateTime RegistrationEndDate { get; set; }
        public bool Periodic { get; set; }
    }
}

RideSharingAPP.WEB/Controllers/AccountInformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RideSharingApp.BLL.DTO;
using RideSharingApp.BLL.Interfaces;
using RideSharingApp.WEB.Models;
using AutoMapper;
using RideSharingApp.BLL.Infrastructure;
using System.Net;

namespace RideSharingApp.WEB.Controllers
{
    public class AccountInformationController : Controller
    {
        const string StaticSalt = "1e58c1047ca24fa6b0661dde402cee179860087f1631ab01eeca6a068f3bbb8a";


        IAccountInformationService accountService;
        public AccountInformationController(IAccountInformationService serv)
        {
            accountService = serv;
        }

        [HttpGet]
        public ActionResult Input()
        {
            return View();
        }

        public string GetIPAddress()
        {
            
            IPHostEntry ipHostInfo = Dns.GetHostEntry(Dns.GetHostName());
            IPAddress ipAddress = ipHostInfo.AddressList[0];

            return ipAddress.ToString();
        }

        [HttpPost]
        public ActionResult Registration(string Login, string Password, string Email, IPAddress iP, UrlHelper Url)
        {
            try
            {
                var newAccount = new AccountInformationDTO { Login = Login, Password = Password, Email = Email };
                accountService.Registration(newAccount);
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError(ex.Property, ex.Message);
            }
            return View(Input());
        }

        protected override void Dispose(bool disposing)
        {
            accountService.Dispose();
            base.Dispose(disposing);
        }
    }
}

RideSharingAPP.WEB/Views/AccountInformation/Input.cshtml
@{
    ViewBag.Title = "Index";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

<style>
    a:hover, a:focus {
        outline: none;
        text-decoration: none;
    }

    .tab {
        background: #200122;
        background: -webkit-linear-gradient(to bottom, #6f0000, #200122);
        background: linear-gradient(to bottom, #6f0000, #200122);
        padding: 40px 50px;
        position: relative;
    }

        .tab:before {
            content: "";
            width: 100%;
            height: 100%;
            display: block;
            position: absolute;
            top: 0;
            left: 0;
            background: linear-gradient(#2e3a6a,#2f0b45);
            opacity: 0.85;
        }

        .tab .nav-tabs {
            border-bottom: none;
            padding: 0 20px;
            position: relative;
        }

            .tab .nav-tabs li {
                margin: 0 30px 0 0;
            }

                .tab .nav-tabs li a {
                    font-size: 18px;
                    color: #fff;
                    border-radius: 0;
                    text-transform: uppercase;
                    background: transparent;
                    padding: 0;
                    margin-right: 0;
                    border: none;
                    border-bottom: 2px solid transparent;
                    opacity: 0.5;
                    position: relative;
                    transition: all 0.5s ease 0s;
                }

                    .tab .nav-tabs li a:hover {
                        background: transparent;
                    }

                .tab .nav-tabs li.active a,
                .tab .nav-tabs li.active a:focus,
                .tab .nav-tabs li.active a:hover {
                    border: none;
                    background: transparent;
                    opacity: 1;
                    border-bottom: 2px solid #eec111;
                    color: #fff;
                }

        .tab .tab-content {
            padding: 20px 0 0 0;
            margin-top: 40px;
            background: transparent;
            z-index: 1;
            position: relative;
        }

    .form-bg {
        background: #ddd;
    }

    .form-horizontal .form-group {
        margin: 0 0 15px 0;
        position: relative;
    }

    .form-horizontal .form-control {
        height: 40px;
        background: rgba(255,255,255,0.2);
        border: none;
        border-radius: 20px;
        box-shadow: none;
        padding: 0 20px;
        font-size: 14px;
        font-weight: bold;
        color: #fff;
        transition: all 0.3s ease 0s;
    }

        .form-horizontal .form-control:focus {
            box-shadow: none;
            outline: 0 none;
        }

    .form-horizontal .form-group label {
        padding: 0 20px;
        color: #7f8291;
        text-transform: capitalize;
        margin-bottom: 10px;
    }

    .form-horizontal .main-checkbox {
        width: 20px;
        height: 20px;
        background: #eec111;
        float: left;
        margin: 5px 0 0 20px;
        border: 1px solid #eec111;
        position: relative;
    }

        .form-horizontal .main-checkbox label {
            width: 20px;
            height: 20px;
            position: absolute;
            top: 0;
            left: 0;
            cursor: pointer;
        }

            .form-horizontal .main-checkbox label:after {
                content: "";
                width: 10px;
                height: 5px;
                position: absolute;
                top: 5px;
                left: 4px;
                border: 3px solid #fff;
                border-top: none;
                border-right: none;
                background: transparent;
                opacity: 0;
                -webkit-transform: rotate(-45deg);
                transform: rotate(-45deg);
            }

        .form-horizontal .main-checkbox input[type=checkbox] {
            visibility: hidden;
        }

            .form-horizontal .main-checkbox input[type=checkbox]:checked + label:after {
                opacity: 1;
            }

    .form-horizontal .text {
        float: left;
        font-size: 14px;
        font-weight: bold;
        color: #fff;
        margin-left: 7px;
        line-height: 20px;
        padding-top: 5px;
        text-transform: capitalize;
    }

    .form-horizontal .btn {
        width: 100%;
        background: #eec111;
        padding: 10px 20px;
        border: none;
        font-size: 14px;
        font-weight: bold;
        color: #fff;
        border-radius: 20px;
        text-transform: uppercase;
        margin: 20px 0 30px 0;
    }

        .form-horizontal .btn:focus {
            background: #eec111;
            color: #fff;
            outline: none;
            box-shadow: none;
        }

    .form-horizontal .forgot-pass {
        border-top: 1px solid #615f6c;
        margin: 0;
        text-align: center;
    }

        .form-horizontal .forgot-pass .btn {
            width: auto;
            background: transparent;
            margin: 30px 0 0 0;
            color: #615f6c;
            text-transform: capitalize;
            transition: all 0.3s ease 0s;
        }

            .form-horizontal .forgot-pass .btn:hover {
                color: #eec111;
            }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">

            <div class="tab" role="tabpanel">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#Section1" aria-controls="home" role="tab" data-toggle="tab">sign in</a></li>
                    <li role="presentation"><a href="#Section2" aria-controls="profile" role="tab" data-toggle="tab">sign up</a></li>
                </ul>
                <!-- Tab panes -->

                <div class="tab-content tabs">
                    
                    <div role="tabpanel" class="tab-pane fade in active" id="Section1">
                        @using (Html.BeginForm("Input", "AccountInformation", new { iP = HttpContext.Current.Request.UserHostAddress, Url = HttpContext.Current.Request.Url }, FormMethod.Post ,new { @class = "form-horizontal" }))
                        {
                        <div class="form-group">
                            <label for="exampleInputEmail1">username</label>
                            @Html.TextBox("Login", null,  new { @type = "login", @class = "form-control"})
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Password</label>
                            @Html.Password("Password", null, new { @type = "password", @class = "form-control" }))
                        </div>
                            <div class="form-group">
                                <div class="main-checkbox">
                                    <input value="None" id="checkbox1" name="check" type="checkbox">
                                    <label for="checkbox1"></label>
                                </div>
                                <span class="text">Keep me Signed in</span>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-default" name="action" value="input">Sign in</button>
                            </div>

                            <div class="form-group forgot-pass">
                                <button type="submit" class="btn btn-default" name="action" value="password_recovery">forgot password</button>
                            </div>
                        }
                    </div>
                    <div role="tabpanel" class="tab-pane fade" id="Section2">
                        @using (Html.BeginForm("Registration", "AccountInformation", FormMethod.Post, new { @class = "form-horizontal" }))
                        {
                        <div class="form-group">
                            <label for="exampleInputEmail1">Login</label>
                            @Html.TextBox("Login", null, new { @type = "login", @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Password</label>
                            @Html.TextBox("Password", null, new { @type = "password", @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Email address</label>
                            @Html.TextBox("Email", null, new { @type = "email", @class = "form-control" })
                        </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-default">Sign up</button>
                                </div>
                        }
                        </div>
                </div>
            </div>

        </div><!-- /.col-md-offset-3 col-md-6 -->
    </div><!-- /.row -->
</div><!-- /.container -->

RideSharingAPP.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>